static const char * const vendor_name[1000] = {
"ASHRAE",
"NIST",
"The Trane Company",
"McQuay International",
"PolarSoft",
"Johnson Controls, Inc.",
"American Auto-Matrix",
"Siemens Schweiz AG",
"Delta Controls",
"Siemens Schweiz AG",
"Schneider Electric",
"TAC",
"Orion Analysis Corporation",
"Teletrol Systems Inc.",
"Cimetrics Technology",
"Cornell University",
"United Technologies Carrier",
"Honeywell Inc.",
"Alerton / Honeywell",
"TAC AB",
"Hewlett-Packard Company",
"Dorsette's Inc.",
"Siemens Schweiz AG",
"York Controls Group",
"Automated Logic Corporation",
"CSI Control Systems International",
"Phoenix Controls Corporation",
"Innovex Technologies, Inc.",
"KMC Controls, Inc.",
"Xn Technologies, Inc.",
"Hyundai Information Technology Co., Ltd.",
"Tokimec Inc.",
"Simplex",
"North Building Technologies Limited",
"Notifier",
"Reliable Controls Corporation",
"Tridium Inc.",
"Sierra Monitor Corporation/FieldServer Technologies",
"Silicon Energy",
"Kieback & Peter GmbH & Co KG",
"Anacon Systems, Inc.",
"Systems Controls & Instruments, LLC",
"Acuity Brands Lighting, Inc.",
"Micropower Manufacturing",
"Matrix Controls",
"METALAIRE",
"ESS Engineering",
"Sphere Systems Pty Ltd.",
"Walker Technologies Corporation",
"H I Solutions, Inc.",
"MBS GmbH",
"SAMSON AG",
"Badger Meter Inc.",
"DAIKIN Industries Ltd.",
"NARA Controls Inc.",
"Mammoth Inc.",
"Liebert Corporation",
"SEMCO Incorporated",
"Air Monitor Corporation",
"TRIATEK, LLC",
"NexLight",
"Multistack",
"TSI Incorporated",
"Weather-Rite, Inc.",
"Dunham-Bush",
"Reliance Electric",
"LCS Inc.",
"Regulator Australia PTY Ltd.",
"Touch-Plate Lighting Controls",
"Amann GmbH",
"RLE Technologies",
"Cardkey Systems",
"SECOM Co., Ltd.",
"ABB Gebäudetechnik AG Bereich NetServ",
"KNX Association cvba",
"Institute of Electrical Installation Engineers of Japan (IEIEJ)",
"Nohmi Bosai, Ltd.",
"Carel S.p.A.",
"UTC Fire & Security España, S.L.",
"Hochiki Corporation",
"Fr. Sauter AG",
"Matsushita Electric Works, Ltd.",
"Mitsubishi Electric Corporation, Inazawa Works",
"Mitsubishi Heavy Industries, Ltd.",
"Xylem, Inc.",
"Yamatake Building Systems Co., Ltd.",
"The Watt Stopper, Inc.",
"Aichi Tokei Denki Co., Ltd.",
"Activation Technologies, LLC",
"Saia-Burgess Controls, Ltd.",
"Hitachi, Ltd.",
"Novar Corp./Trend Control Systems Ltd.",
"Mitsubishi Electric Lighting Corporation",
"Argus Control Systems, Ltd.",
"Kyuki Corporation",
"Richards-Zeta Building Intelligence, Inc.",
"Scientech R&D, Inc.",
"VCI Controls, Inc.",
"Toshiba Corporation",
"Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works",
"Custom Mechanical Equipment, LLC",
"ClimateMaster",
"ICP Panel-Tec, Inc.",
"D-Tek Controls",
"NEC Engineering, Ltd.",
"PRIVA BV",
"Meidensha Corporation",
"JCI Systems Integration Services",
"Freedom Corporation",
"Neuberger Gebäudeautomation GmbH",
"eZi Controls",
"Leviton Manufacturing",
"Fujitsu Limited",
"Emerson Network Power",
"S. A. Armstrong, Ltd.",
"Visonet AG",
"M&M Systems, Inc.",
"Custom Software Engineering",
"Nittan Company, Limited",
"Elutions Inc. (Wizcon Systems SAS)",
"Pacom Systems Pty., Ltd.",
"Unico, Inc.",
"Ebtron, Inc.",
"Scada Engine",
"AC Technology Corporation",
"Eagle Technology",
"Data Aire, Inc.",
"ABB, Inc.",
"Transbit Sp. z o. o.",
"Toshiba Carrier Corporation",
"Shenzhen Junzhi Hi-Tech Co., Ltd.",
"Tokai Soft",
"Blue Ridge Technologies",
"Veris Industries",
"Centaurus Prime",
"Sand Network Systems",
"Regulvar, Inc.",
"AFDtek Division of Fastek International Inc.",
"PowerCold Comfort Air Solutions, Inc.",
"I Controls",
"Viconics Electronics, Inc.",
"Yaskawa America, Inc.",
"DEOS control systems GmbH",
"Digitale Mess- und Steuersysteme AG",
"Fujitsu General Limited",
"Project Engineering S.r.l.",
"Sanyo Electric Co., Ltd.",
"Integrated Information Systems, Inc.",
"Temco Controls, Ltd.",
"Airtek International Inc.",
"Advantech Corporation",
"Titan Products, Ltd.",
"Regel Partners",
"National Environmental Product",
"Unitec Corporation",
"Kanden Engineering Company",
"Messner Gebäudetechnik GmbH",
"Integrated.CH",
"Price Industries",
"SE-Elektronic GmbH",
"Rockwell Automation",
"Enflex Corp.",
"ASI Controls",
"SysMik GmbH Dresden",
"HSC Regelungstechnik GmbH",
"Smart Temp Australia Pty.  Ltd.",
"Cooper Controls",
"Duksan Mecasys Co., Ltd.",
"Fuji IT Co., Ltd.",
"Vacon Plc",
"Leader Controls",
"Cylon Controls, Ltd.",
"Compas",
"Mitsubishi Electric Building Techno-Service Co., Ltd.",
"Building Control Integrators",
"ITG Worldwide (M) Sdn Bhd",
"Lutron Electronics Co., Inc.",
"Cooper-Atkins Corporation",
"LOYTEC Electronics GmbH",
"ProLon",
"Mega Controls Limited",
"Micro Control Systems, Inc.",
"Kiyon, Inc.",
"Dust Networks",
"Advanced Building Automation Systems",
"Hermos AG",
"CEZIM",
"Softing",
"Lynxspring, Inc.",
"Schneider Toshiba Inverter Europe",
"Danfoss Drives A/S",
"Eaton Corporation",
"Matyca S.A.",
"Botech AB",
"Noveo, Inc.",
"AMEV",
"Yokogawa Electric Corporation",
"GFR Gesellschaft für Regelungstechnik",
"Exact Logic",
"Mass Electronics Pty Ltd dba Innotech Control Systems Australia",
"Kandenko Co., Ltd.",
"DTF, Daten-Technik Fries",
"Klimasoft, Ltd.",
"Toshiba Schneider Inverter Corporation",
"Control Applications, Ltd.",
"KDT Systems Co., Ltd.",
"Onicon Incorporated",
"Automation Displays, Inc.",
"Control Solutions, Inc.",
"Remsdaq Limited",
"NTT Facilities, Inc.",
"VIPA GmbH",
"TSC21 Association of Japan",
"Strato Automation",
"HRW Limited",
"Lighting Control & Design, Inc.",
"Mercy Electronic and Electrical Industries",
"Samsung SDS Co., Ltd",
"Impact Facility Solutions, Inc.",
"Aircuity",
"Control Techniques, Ltd.",
"OpenGeneral Pty., Ltd.",
"WAGO Kontakttechnik GmbH & Co. KG",
"Cerus Industrial",
"Chloride Power Protection Company",
"Computrols, Inc.",
"Phoenix Contact GmbH & Co. KG",
"Grundfos Management A/S",
"Ridder Drive Systems",
"Soft Device SDN BHD",
"Integrated Control Technology Limited",
"AIRxpert Systems, Inc.",
"Microtrol Limited",
"Red Lion Controls",
"Digital Electronics Corporation",
"Ennovatis GmbH",
"Serotonin Software Technologies, Inc.",
"LS Industrial Systems Co., Ltd.",
"Square D Company",
"S Squared Innovations, Inc.",
"Aricent Ltd.",
"EtherMetrics, LLC",
"Industrial Control Communications, Inc.",
"Paragon Controls, Inc.",
"A. O. Smith Corporation",
"Contemporary Control Systems, Inc.",
"Intesis Software SL",
"Ingenieurgesellschaft N. Hartleb mbH",
"Heat-Timer Corporation",
"Ingrasys Technology, Inc.",
"Costerm Building Automation",
"WILO SE",
"Embedia Technologies Corp.",
"Technilog",
"HR Controls Ltd. & Co. KG",
"Lennox International, Inc.",
"RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG",
"Thermomax, Ltd.",
"ELCON Electronic Control, Ltd.",
"Larmia Control AB",
"BACnet Stack at SourceForge",
"G4S Security Services A/S",
"Exor International S.p.A.",
"Cristal Controles",
"Regin AB",
"Dimension Software, Inc. ",
"SynapSense Corporation",
"Beijing Nantree Electronic Co., Ltd.",
"Camus Hydronics Ltd.",
"Kawasaki Heavy Industries, Ltd. ",
"Critical Environment Technologies",
"ILSHIN IBS Co., Ltd.",
"ELESTA Energy Control AG",
"KROPMAN Installatietechniek",
"Baldor Electric Company",
"INGA mbH",
"GE Consumer & Industrial",
"Functional Devices, Inc.",
"ESAC",
"M-System Co., Ltd.",
"Yokota Co., Ltd.",
"Hitranse Technology Co., LTD",
"Vigilent Corporation",
"Kele, Inc.",
"Opera Electronics, Inc.",
"Gentec",
"Embedded Science Labs, LLC",
"Parker Hannifin Corporation",
"MaCaPS International Limited",
"Link4 Corporation",
"Romutec Steuer-u. Regelsysteme GmbH ",
"Pribusin, Inc.",
"Advantage Controls",
"Critical Room Control",
"LEGRAND",
"Tongdy Control Technology Co., Ltd. ",
"ISSARO Integrierte Systemtechnik",
"Pro-Dev Industries",
"DRI-STEEM",
"Creative Electronic GmbH",
"Swegon AB",
"Jan Brachacek",
"Hitachi Appliances, Inc.",
"Real Time Automation, Inc.",
"ITEC Hankyu-Hanshin Co.",
"Cyrus E&M Engineering Co., Ltd. ",
"Badger Meter",
"Cirrascale Corporation",
"Elesta GmbH Building Automation ",
"Securiton",
"OSlsoft, Inc.",
"Hanazeder Electronic GmbH ",
"Honeywell Security Deutschland, Novar GmbH",
"Siemens Industry, Inc.",
"ETM Professional Control GmbH",
"Meitav-tec, Ltd.",
"Janitza Electronics GmbH ",
"MKS Nordhausen",
"De Gier Drive Systems B.V. ",
"Cypress Envirosystems",
"SMARTron s.r.o.",
"Verari Systems, Inc.",
"K-W Electronic Service, Inc.",
"ALFA-SMART Energy Management",
"Telkonet, Inc.",
"Securiton GmbH",
"Cemtrex, Inc.",
"Performance Technologies, Inc.",
"Xtralis (Aust) Pty Ltd",
"TROX GmbH",
"Beijing Hysine Technology Co., Ltd",
"RCK Controls, Inc.",
"Distech Controls SAS",
"Novar/Honeywell",
"The S4 Group, Inc.",
"Schneider Electric",
"LHA Systems",
"GHM engineering Group, Inc.",
"Cllimalux S.A.",
"VAISALA Oyj",
"COMPLEX (Beijing) Technology, Co., LTD.",
"SCADAmetrics",
"POWERPEG NSI Limited",
"BACnet Interoperability Testing Services, Inc.",
"Teco a.s.",
"Plexus Technology, Inc.",
"Energy Focus, Inc.",
"Powersmiths International Corp.",
"Nichibei Co., Ltd.",
"HKC Technology Ltd.",
"Ovation Networks, Inc.",
"Setra Systems",
"AVG Automation",
"ZXC Ltd.",
"Byte Sphere",
"Generiton Co., Ltd.",
"Holter Regelarmaturen GmbH & Co. KG",
"Bedford Instruments, LLC",
"Standair Inc.",
"WEG Automation - R&D",
"Prolon Control Systems ApS",
"Inneasoft",
"ConneXSoft GmbH",
"CEAG Notlichtsysteme GmbH",
"Distech Controls Inc.",
"Industrial Technology Research Institute",
"ICONICS, Inc.",
"IQ Controls s.c.",
"OJ Electronics A/S",
"Rolbit Ltd.",
"Synapsys Solutions Ltd.",
"ACME Engineering Prod. Ltd.",
"Zener Electric Pty, Ltd.",
"Selectronix, Inc.",
"Gorbet & Banerjee, LLC.",
"IME",
"Stephen H. Dawson Computer Service",
"Accutrol, LLC",
"Schneider Elektronik GmbH",
"Alpha-Inno Tec GmbH",
"ADMMicro, Inc.",
"Greystone Energy Systems, Inc.",
"CAP Technologie",
"KeRo Systems",
"Domat Control System s.r.o.",
"Efektronics Pty. Ltd.",
"Hekatron Vertriebs GmbH",
"Securiton AG",
"Carlo Gavazzi Controls SpA",
"Chipkin Automation Systems",
"Savant Systems, LLC",
"Simmtronic Lighting Controls",
"Abelko Innovation AB",
"Seresco Technologies Inc.",
"IT Watchdogs",
"Automation Assist Japan Corp.",
"Thermokon Sensortechnik GmbH",
"EGauge Systems, LLC",
"Quantum Automation (ASIA) PTE, Ltd.",
"Toshiba Lighting & Technology Corp.",
"SPIN Engenharia de Automação Ltda.",
"Logistics Systems & Software Services India PVT. Ltd.",
"Delta Controls Integration Products",
"Focus Media",
"LUMEnergi Inc.",
"Kara Systems",
"RF Code, Inc.",
"Fatek Automation Corp.",
"JANDA Software Company, LLC",
"Open System Solutions Limited",
"Intelec Systems PTY Ltd.",
"Ecolodgix, LLC",
"Douglas Lighting Controls",
"iSAtech GmbH",
"AREAL",
"Beckhoff Automation GmbH",
"IPAS GmbH",
"KE2 Therm Solutions",
"Base2Products",
"DTL Controls, LLC",
"INNCOM International, Inc.",
"BTR Netcom GmbH",
"Greentrol Automation, Inc",
"BELIMO Automation AG",
"Samsung Heavy Industries Co, Ltd",
"Triacta Power Technologies, Inc.",
"Globestar Systems",
"MLB Advanced Media, LP",
"SWG Stuckmann Wirtschaftliche Gebäudesysteme GmbH",
"SensorSwitch",
"Multitek Power Limited",
"Aquametro AG",
"LG Electronics Inc.",
"Electronic Theatre Controls, Inc.",
"Mitsubishi Electric Corporation Nagoya Works",
"Delta Electronics, Inc.",
"Elma Kurtalj, Ltd.",
"ADT Fire and Security Sp. A.o.o.",
"Nedap Security Management",
"ESC Automation Inc.",
"DSP4YOU Ltd.",
"GE Sensing and Inspection Technologies",
"Embedded Systems SIA",
"BEFEGA GmbH",
"Baseline Inc.",
"M2M Systems Integrators",
"OEMCtrl",
"Clarkson Controls Limited",
"Rogerwell Control System Limited",
"SCL Elements",
"Hitachi Ltd.",
"Newron System SA",
"BEVECO Gebouwautomatisering BV",
"Streamside Solutions",
"Yellowstone Soft",
"Oztech Intelligent Systems Pty Ltd.",
"Novelan GmbH",
"Flexim Americas Corporation",
"ICP DAS Co., Ltd.",
"CARMA Industries Inc.",
"Log-One Ltd.",
"TECO Electric & Machinery Co., Ltd.",
"ConnectEx, Inc.",
"Turbo DDC Südwest",
"Quatrosense Environmental Ltd.",
"Fifth Light Technology Ltd.",
"Scientific Solutions, Ltd.",
"Controller Area Network Solutions (M) Sdn Bhd",
"RESOL - Elektronische Regelungen GmbH",
"RPBUS LLC",
"BRS Sistemas Eletronicos",
"WindowMaster A/S",
"Sunlux Technologies Ltd.",
"Measurlogic",
"Frimat GmbH",
"Spirax Sarco",
"Luxtron",
"Raypak Inc",
"Air Monitor Corporation",
"Regler Och Webbteknik Sverige (ROWS)",
"Intelligent Lighting Controls Inc.",
"Sanyo Electric Industry Co., Ltd",
"E-Mon Energy Monitoring Products",
"Digital Control Systems",
"ATI Airtest Technologies, Inc.",
"SCS SA",
"HMS Industrial Networks AB",
"Shenzhen Universal Intellisys Co Ltd",
"EK Intellisys Sdn Bhd",
"SysCom",
"Firecom, Inc.",
"ESA Elektroschaltanlagen Grimma GmbH",
"Kumahira Co Ltd",
"Hotraco",
"SABO Elektronik GmbH",
"Equip'Trans",
"TCS Basys Controls",
"FlowCon International A/S",
"ThyssenKrupp Elevator Americas",
"Abatement Technologies",
"Continental Control Systems, LLC",
"WISAG Automatisierungstechnik GmbH & Co KG",
"EasyIO",
"EAP-Electric GmbH",
"Hardmeier",
"Mircom Group of Companies",
"Quest Controls",
"Mestek, Inc",
"Pulse Energy",
"Tachikawa Corporation",
"University of Nebraska-Lincoln",
"Redwood Systems",
"PASStec Industrie-Elektronik GmbH",
"NgEK, Inc.",
"t-mac Technologies",
"Jireh Energy Tech Co., Ltd.",
"Enlighted Inc.",
"El-Piast Sp. Z o.o",
"NetxAutomation Software GmbH",
"Invertek Drives",
"Deutschmann Automation GmbH & Co. KG",
"EMU Electronic AG",
"Phaedrus Limited",
"Sigmatek GmbH & Co KG",
"Marlin Controls",
"Circutor, SA",
"UTC Fire & Security",
"DENT Instruments, Inc.",
"FHP Manufacturing Company - Bosch Group",
"GE Intelligent Platforms",
"Inner Range Pty Ltd",
"GLAS Energy Technology",
"MSR-Electronic-GmbH",
"Energy Control Systems, Inc.",
"EMT Controls",
"Daintree Networks Inc.",
"EURO ICC d.o.o",
"TE Connectivity Energy",
"GEZE GmbH",
"NEC Corporation",
"Ho Cheung International Company Limited",
"Sharp Manufacturing Systems Corporation",
"DOT CONTROLS a.s.",
"BeaconMedæs",
"Midea Commercial Aircon",
"WattMaster Controls",
"Kamstrup A/S",
"CA Computer Automation GmbH",
"Laars Heating Systems Company",
"Hitachi Systems, Ltd.",
"Fushan AKE Electronic Engineering Co., Ltd.",
"Toshiba International Corporation",
"Starman Systems, LLC",
"Samsung Techwin Co., Ltd.",
"ISAS-Integrated Switchgear and Systems P/L",
"Reserved for ASHRAE",
"Obvius",
"Marek Guzik",
"Vortek Instruments, LLC",
"Universal Lighting Technologies",
"Myers Power Products, Inc.",
"Vector Controls GmbH",
"Crestron Electronics, Inc.",
"A&E Controls Limited",
"Projektomontaza A.D.",
"Freeaire Refrigeration",
"Aqua Cooler Pty Limited",
"Basic Controls",
"GE Measurement and Control Solutions Advanced Sensors",
"EQUAL Networks",
"Millennial Net",
"APLI Ltd",
"Electro Industries/GaugeTech",
"SangMyung University",
"Coppertree Analytics, Inc.",
"CoreNetiX GmbH",
"Acutherm",
"Dr. Riedel Automatisierungstechnik GmbH",
"Shina System Co., Ltd",
"Iqapertus",
"PSE Technology",
"BA Systems",
"BTICINO",
"Monico, Inc.",
"iCue",
"tekmar Control Systems Ltd.",
"Control Technology Corporation",
"GFAE GmbH",
"BeKa Software GmbH",
"Isoil Industria SpA",
"Home Systems Consulting SpA",
"Socomec",
"Everex Communications, Inc.",
"Ceiec Electric Technology",
"Atrila GmbH",
"WingTechs",
"Shenzhen Mek Intellisys Pte Ltd.",
"Nestfield Co., Ltd.",
"Swissphone Telecom AG",
"PNTECH JSC",
"Horner APG, LLC",
"PVI Industries, LLC",
"Ela-compil",
"Pegasus Automation International LLC",
"Wight Electronic Services Ltd.",
"Marcom",
"Exhausto A/S",
"Dwyer Instruments, Inc.",
"Link GmbH",
"Oppermann Regelgerate GmbH",
"NuAire, Inc.",
"Nortec Humidity, Inc.",
"Bigwood Systems, Inc.",
"Enbala Power Networks",
"Inter Energy Co., Ltd.",
"ETC",
"COMELEC S.A.R.L",
"Pythia Technologies",
"TrendPoint Systems, Inc.",
"AWEX",
"Eurevia",
"Kongsberg E-lon AS",
"FlaktWoods",
"E + E Elektronik GES M.B.H.",
"ARC Informatique",
"SKIDATA AG",
"WSW Solutions",
"Trefon Electronic GmbH",
"Dongseo System",
"Kanontec Intelligence Technology Co., Ltd.",
"EVCO S.p.A.",
"Accuenergy (CANADA) Inc.",
"SoftDEL",
"Orion Energy Systems, Inc.",
"Roboticsware",
"DOMIQ Sp. z o.o.",
"Solidyne",
"Elecsys Corporation",
"Conditionaire International Pty. Limited",
"Quebec, Inc.",
"Homerun Holdings",
"Murata Americas",
"Comptek",
"Westco Systems, Inc.",
"Advancis Software & Services GmbH",
"Intergrid, LLC",
"Markerr Controls, Inc.",
"Toshiba Elevator and Building Systems Corporation",
"Spectrum Controls, Inc.",
"Mkservice",
"Fox Thermal Instruments",
"SyxthSense Ltd",
"DUHA System S R.O.",
"NIBE",
"Melink Corporation",
"Fritz-Haber-Institut",
"MTU Onsite Energy GmbH, Gas Power Systems",
"Omega Engineering, Inc.",
"Avelon",
"Ywire Technologies, Inc.",
"M.R. Engineering Co., Ltd.",
"Lochinvar, LLC",
"Sontay Limited",
"GRUPA Slawomir Chelminski",
"Arch Meter Corporation",
"Senva, Inc.",
"Reserved for ASHRAE",
"FM-Tec",
"Systems Specialists, Inc.",
"SenseAir",
"AB IndustrieTechnik Srl",
"Cortland Research, LLC",
"MediaView",
"VDA Elettronica",
"CSS, Inc.",
"Tek-Air Systems, Inc.",
"ICDT",
"The Armstrong Monitoring Corporation",
"DIXELL S.r.l",
"Lead System, Inc.",
"ISM EuroCenter S.A.",
"TDIS",
"Trade FIDES",
"Knürr GmbH (Emerson Network Power)",
"Resource Data Management",
"Abies Technology, Inc.",
"Amalva",
"MIRAE Electrical Mfg. Co., Ltd.",
"HunterDouglas Architectural Projects Scandinavia ApS",
"RUNPAQ Group Co., Ltd",
"Unicard SA",
"IE Technologies",
"Ruskin Manufacturing",
"Calon Associates Limited",
"Contec Co., Ltd.",
"iT GmbH",
"Autani Corporation",
"Christian Fortin",
"HDL",
"IPID Sp. Z.O.O Limited",
"Fuji Electric Co., Ltd",
"View, Inc.",
"Samsung S1 Corporation",
"New Lift",
"VRT Systems",
"Motion Control Engineering, Inc.",
"Weiss Klimatechnik GmbH",
"Elkon",
"Eliwell Controls S.r.l.",
"Japan Computer Technos Corp",
"Rational Network ehf",
"Magnum Energy Solutions, LLC",
"MelRok",
"VAE Group",
"LGCNS",
"Berghof Automationstechnik GmbH",
"Quark Communications, Inc.",
"Sontex",
"mivune AG",
"Panduit",
"Smart Controls, LLC",
"Compu-Aire, Inc.",
"Sierra",
"ProtoSense Technologies",
"Eltrac Technologies Pvt Ltd",
"Bektas Invisible Controls GmbH",
"Entelec",
"INNEXIV",
"Covenant",
"Davitor AB",
"TongFang Technovator",
"Building Robotics, Inc.",
"HSS-MSR UG",
"FramTack LLC",
"B. L. Acoustics, Ltd.",
"Traxxon Rock Drills, Ltd",
"Franke",
"Wurm GmbH & Co",
"AddENERGIE",
"Mirle Automation Corporation",
"Ibis Networks",
"ID-KARTA s.r.o.",
"Anaren, Inc.",
"Span, Incorporated",
"Bosch Thermotechnology Corp",
"DRC Technology S.A.",
"Shanghai Energy Building Technology Co, Ltd",
"Fraport AG",
"Flowgroup",
"Skytron Energy, GmbH",
"ALTEL Wicha, Golda Sp. J.",
"Drupal",
"Axiomatic Technology, Ltd",
"Bohnke + Partner",
"Function 1",
"Optergy Pty, Ltd",
"LSI Virticus",
"Konzeptpark GmbH",
"Hubbell Building Automation, Inc.",
"eCurv, Inc.",
"Agnosys GmbH",
"Shanghai Sunfull Automation Co., LTD",
"Kurz Instruments, Inc.",
"Cias Elettronica S.r.l.",
"Multiaqua, Inc.",
"BlueBox",
"Sensidyne",
"Viessmann Elektronik GmbH",
"ADFweb.com srl",
"Gaylord Industries",
"Majur Ltd.",
"Shanghai Huilin Technology Co., Ltd.",
"Exotronic",
"Safecontrol spol s.r.o.",
"Amatis",
"Universal Electric Corporation",
"iBACnet",
"Reserved for ASHRAE",
"Smartrise Engineering, Inc.",
"Miratron, Inc.",
"SmartEdge",
"Mitsubishi Electric Australia Pty Ltd",
"Triangle Research International Ptd Ltd",
"Produal Oy",
"Milestone Systems A/S",
"Trustbridge",
"Feedback Solutions",
"IES",
"GE Critical Power",
"Riptide IO",
"Messerschmitt Systems AG",
"Dezem Energy Controlling",
"MechoSystems",
"evon GmbH",
"CS Lab GmbH",
"8760 Enterprises, Inc.",
"Touche Controls",
"Ontrol Teknik Malzeme San. ve Tic. A.S.",
"Uni Control System Sp. Z o.o.",
"Weihai Ploumeter Co., Ltd",
"Elcom International Pvt. Ltd",
"Philips Lighting",
"AutomationDirect",
"Paragon Robotics",
"SMT System & Modules Technology AG",
"OS Technology Service and Trading Co., LTD",
"CMR Controls Ltd",
"Innovari, Inc.",
"ABB Control Products",
"Gesellschaft fur Gebäudeautomation mbH",
"RODI Systems Corp.",
"Nextek Power Systems",
"Creative Lighting",
"WaterFurnace International",
"Mercury Security",
"Hisense (Shandong) Air-Conditioning Co., Ltd.",
"Layered Solutions, Inc.",
"Leegood Automatic System, Inc.",
"Shanghai Restar Technology Co., Ltd.",
"Reimann Ingenieurbüro",
"LynTec",
"HTP",
"Elkor Technologies, Inc.",
"Bentrol Pty Ltd",
"Team-Control Oy",
"NextDevice, LLC",
"GLOBAL CONTROL 5 Sp. z o.o.",
"King I Electronics Co., Ltd",
"SAMDAV",
"Next Gen Industries Pvt. Ltd.",
"Entic LLC",
"ETAP",
"Moralle Electronics Limited",
"Leicom AG",
"Watts Regulator Company",
"S.C. Orbtronics S.R.L.",
"Gaussan Technologies",
"WEBfactory GmbH",
"Ocean Controls",
"Messana  Air-Ray Conditioning s.r.l.",
"Hangzhou BATOWN Technology Co. Ltd.",
"Reasonable Controls",
"Servisys, Inc.",
"halstrup-walcher GmbH",
"SWG Automation Fuzhou Limited",
"KSB Aktiengesellschaft",
"Hybryd Sp. z o.o.",
"Helvatron AG",
"Oderon Sp. Z.O.O.",
"miko",
"Exodraft",
"Hochhuth GmbH",
"Integrated System Technologies Ltd.",
"Shanghai Cellcons Controls Co., Ltd",
"Emme Controls, LLC",
"Field Diagnostic Services, Inc.",
"Ges Teknik A.S.",
"Global Power Products, Inc.",
"Option NV",
"BV-Control AG",
"Sigren Engineering AG",
"Shanghai Jaltone Technology Co., Ltd.",
"MaxLine Solutions Ltd",
"Kron Instrumentos Elétricos Ltda",
"Thermo Matrix",
"Infinite Automation Systems, Inc.",
"Vantage",
"Elecon Measurements Pvt Ltd",
"TBA",
"Carnes Company",
"Harman Professional",
"Nenutec Asia Pacific Pte Ltd",
"Gia NV",
"Kepware Tehnologies",
"Temperature Electronics Ltd",
"Packet Power",
"Project Haystack Corporation",
"DEOS Controls Americas Inc.",
"Senseware Inc",
"MST Systemtechnik AG",
"Lonix Ltd",
"GMC-I Messtechnik GmbH",
"Aviosys International Inc.",
"Efficient Building Automation Corp.",
"Accutron Instruments Inc.",
"Vermont Energy Control Systems LLC",
"DCC Dynamics",
"Brück Electronic GmbH",
"Reserved for ASHRAE",
"NGBS Hungary Ltd.",
"ILLUM Technology, LLC",
"Delta Controls Germany Limited",
"S+T Service & Technique S.A.",
"SimpleSoft",
"Candi Controls, Inc.",
"EZEN Solution Inc.",
"Fujitec Co. Ltd.",
"Terralux",
"Annicom",
"Bihl+Wiedemann GmbH",
"Daper, Inc.",
"Schüco International KG",
"Otis Elevator Company",
"Fidelix Oy",
"RAM GmbH Mess- und Regeltechnik",
"WEMS",
"Ravel Electronics Pvt Ltd",
"OmniMagni",
"Echelon",
"Intellimeter Canada, Inc.",
"Bithouse Oy",
"Reserved for ASHRAE",
"BuildPulse",
"Shenzhen 1000 Building Automation Co. Ltd",
"AED Engineering GmbH",
"Güntner GmbH & Co. KG",
"KNXlogic",
"CIM Environmental Group",
"Flow Control",
"Lumen Cache, Inc.",
"Ecosystem",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Reserved for ASHRAE",
};
